A_AMB_INT = 'Ambiguous Interfaces'
A_FEA_CON = 'Feature Concentration'
A_UNS_DEP = 'Unstable Dependency'
A_CYC_DEP = 'Cyclic Dependency'
A_DEN_STR = 'Dense Structure'
A_SCA_FUN = 'Scattered Functionality'
A_GOD_COM = 'God Component'

D_UNN_ABS = "Unnecessary Abstraction"
D_IMP_ABS = "Imperative Abstraction"
D_MUL_ABS = "Multifaceted Abstraction"
D_UNUT_ABS = "Unutilized Abstraction"
D_DUP_ABS = "Duplicate Abstraction"
D_FEA_ENV = "Feature Envy"
D_DEF_ENC = "Deficient Encapsulation"
D_UXP_ENC = "Unexploited Encapsulation"
D_BRO_MOD = "Broken Modularization"
D_INS_MOD = "Insufficient Modularization"
D_HUB_MOD = "Hub-like Modularization"
D_CYC_MOD = "Cyclically-dependent Modularization"
D_WID_HIE = "Wide Hierarchy"
D_DEE_HIE = "Deep Hierarchy"
D_MUL_HIE = "Multipath Hierarchy"
D_CYC_HIE = "Cyclic Hierarchy"
D_REB_HIE = "Rebellious Hierarchy"
D_UNF_HIE = "Unfactored Hierarchy"
D_MIS_HIE = "Missing Hierarchy"
D_BRO_HIE = "Broken Hierarchy"

I_LONG_MTD = "Long Method"
I_COMP_MTD = "Complex Method"
I_LONG_PARAM_LIST = "Long Parameter List"
I_LONG_ID = "Long Identifier"
I_LONG_STMT = "Long Statement"
I_COMP_COND = "Complex Conditional"
I_VIRTUAL_CALL = "Virtual Method Call from Constructor"
I_EMTY_CATCH = "Empty Catch Block"
I_MAGIC_NO = "Magic Number"
I_DUP_CODE = "Duplicate Code"
I_MIS_DEF = "Missing Default"